### ISSUE TITLE
spring boot 1.4.2 cannot work

### ISSUE THREAD

**Issue by yangxuqiang1111** [ttddyy/datasource-proxy-examples#9] opened 2017-08-04 08:53 UTC
@Bean(name = "skyDataSource")
    @Primary
    public DataSource masterDataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName(driverClass);
        dataSource.setUrl(url);
        dataSource.setUsername(user);
        dataSource.setPassword(password);
        dataSource.setInitialSize(2);
        dataSource.setMaxActive(50);
        dataSource.setMinIdle(2);
        dataSource.setMaxWait(5000L);
        DataSource resultDataSource = ProxyDataSourceBuilder.create(dataSource).name("MyDS")
                .multiline().logQueryBySlf4j(SLF4JLogLevel.INFO).build();
        return resultDataSource;
    }
i use this way,but which cannot work,I use spring boot which version 1.4.2 ,datasource-proxy version is 1.4.2

**Comment by ttddyy** [comment] 2017-08-04 14:03
duplicate of https://github.com/ttddyy/datasource-proxy/issues/40

**Closed as completed by ttddyy** 2017-08-04 14:03 UTC
